services:
  db:
    image: mysql:8.0
    container_name: crema-db
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'coffeematch'
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

  backend:
    build: ../backend
    container_name: crema-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/coffeematch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '1234'
    depends_on:
      - db
    restart: always

  frontend:
    build: ../frontend
    container_name: crema-frontend
    ports:
      - "5173:80"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
